# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Song.create(
  [
    {title: 'Like A Rose', artist: 'Ashley Monroe', critic: 'NYT Caramanica', rank: 3},
    {title: 'Acid Rap', artist: 'Chance the Rapper', critic: 'NYT Caramanica', rank: 8},
    {title: 'Nothing Was the Same', artist: 'Drake', critic: 'NYT Caramanica', rank: 1},
    {title: 'Days Are Gone', artist: 'Haim', critic: 'NYT Caramanica', rank: 9},
    {title: 'Unamed Album', artist: 'Jai Paul', critic: 'NYT Caramanica', rank: 4},
    {title: 'Yeezus', artist: 'Kanye West', critic: 'NYT Caramanica', rank: 2},
    {title: 'Y.R.N.', artist: 'Migos', critic: 'NYT Caramanica', rank: 7},
    {title: 'My Name Is My Name', artist: 'Pusha T', critic: 'NYT Caramanica', rank: 5},
    {title: 'Night Time, My Time', artist: 'Sky Ferreira', critic: 'NYT Caramanica', rank: 6},
    {title: 'Beach House 2', artist: 'Ty Dolla Sign', critic: 'NYT Caramanica', rank: 10},
    {title: 'The World According to Andy Bey', artist: 'Andy Bey', critic: 'NYT Chinen', rank: 4},
    {title: 'Like a Rose', artist: 'Ashley Monroe', critic: 'NYT Chinen', rank: 5},
    {title: 'Dream River', artist: 'Bill Callahan', critic: 'NYT Chinen', rank: 3},
    {title: 'WomanChild', artist: 'Cécile McLorin Salvant', critic: 'NYT Chinen', rank: 10},
    {title: 'The Sirens', artist: 'Chris Potter', critic: 'NYT Chinen', rank: 8},
    {title: 'Chants', artist: 'Craig Taborn Trio', critic: 'NYT Chinen', rank: 1},
    {title: 'Time Travel', artist: 'Dave Douglas Quintet', critic: 'NYT Chinen', rank: 6},
    {title: 'Doris', artist: 'Earl Sweatshirt', critic: 'NYT Chinen', rank: 9},
    {title: 'City of Asylum', artist: 'Eric Revis, Kris Davis, Andrew Cyrille', critic: 'NYT Chinen', rank: 7},
    {title: 'Without a Net', artist: 'Wayne Shorter Quartet', critic: 'NYT Chinen', rank: 2},
    {title: 'The Next Day', artist: 'David Bowie', critic: 'NYT Pareles', rank: 7},
    {title: 'The Electric Lady', artist: 'Janelle Monáe', critic: 'NYT Pareles', rank: 6},
    {title: 'Once I Was an Eagle', artist: 'Laura Marling', critic: 'NYT Pareles', rank: 2},
    {title: 'Sing to the Moon', artist: 'Laura Mvula', critic: 'NYT Pareles', rank: 9},
    {title: 'Pure Heroine', artist: 'Lorde', critic: 'NYT Pareles', rank: 1},
    {title: 'Matangi', artist: 'M.I.A.', critic: 'NYT Pareles', rank: 5},
    {title: 'Hesitation Marks', artist: 'Nine Inch Nails', critic: 'NYT Pareles', rank: 4},
    {title: 'Kaani', artist: 'Tal National', critic: 'NYT Pareles', rank: 8},
    {title: 'Excavation', artist: 'The Haxan Cloak', critic: 'NYT Pareles', rank: 10},
    {title: 'Modern Vampires of the City', artist: 'Vampire Weekend', critic: 'NYT Pareles', rank: 3},
    {title: 'Life in the Sugar Candle Mines', artist: 'Black Host', critic: 'NYT Ratliff', rank: 6},
    {title: 'Coming Apart', artist: 'Body/Head', critic: 'NYT Ratliff', rank: 3},
    {title: 'WomanChild', artist: 'Cécile McLorin Salvant', critic: 'NYT Ratliff', rank: 1},
    {title: 'Chants', artist: 'Craig Taborn Trio', critic: 'NYT Ratliff', rank: 5},
    {title: 'Sunbather', artist: 'Deafheaven', critic: 'NYT Ratliff', rank: 2},
    {title: '3.0', artist: 'Marc Anthony', critic: 'NYT Ratliff', rank: 7},
    {title: 'Mestres Navegantes: EdiÃ§Ã£o Cariri', artist: 'Mestres Navegantes: EdiÃ§Ã£o Cariri', critic: 'NYT Ratliff', rank: 4},
    {title: 'Woman', artist: 'Rhye', critic: 'NYT Ratliff', rank: 10},
    {title: 'Night Time, My Time', artist: 'Sky Ferreira', critic: 'NYT Ratliff', rank: 8},
    {title: 'Greater Than', artist: 'Tye Tribbett', critic: 'NYT Ratliff', rank: 9},
    {title: 'Reflektor', artist: 'Arcade Fire', critic: 'Rolling Stone', rank: 5},
    {title: 'AM', artist: 'Arctic Monkeys', critic: 'Rolling Stone', rank: 9},
    {title: 'Like A Rose', artist: 'Ashley Monroe', critic: 'Rolling Stone', rank: 18},
    {title: 'Amok', artist: 'Atoms For Peace', critic: 'Rolling Stone', rank: 15},
    {title: 'TRUE', artist: 'Avicii', critic: 'Rolling Stone', rank: 45},
    {title: 'Song Reader', artist: 'Beck', critic: 'Rolling Stone', rank: 50},
    {title: 'Fade Away Ep', artist: 'Best Coast', critic: 'Rolling Stone', rank: 35},
    {title: 'Nomad', artist: 'Bombino', critic: 'Rolling Stone', rank: 29},
    {title: 'Acid Rap', artist: 'Chance the Rapper', critic: 'Rolling Stone', rank: 26},
    {title: 'The Bones Of What You Believe', artist: 'Chvrches', critic: 'Rolling Stone', rank: 32},
    {title: 'Random Access Memories', artist: 'Daft Punk', critic: 'Rolling Stone', rank: 3},
    {title: 'Old', artist: 'Danny Brown', critic: 'Rolling Stone', rank: 17},
    {title: 'The Next Day', artist: 'David Bowie', critic: 'Rolling Stone', rank: 16},
    {title: 'Settle', artist: 'Disclosure', critic: 'Rolling Stone', rank: 13},
    {title: 'Nothing Was The Same', artist: 'Drake', critic: 'Rolling Stone', rank: 14},
    {title: 'Doris', artist: 'Earl Sweatshirt', critic: 'Rolling Stone', rank: 42},
    {title: 'The Diving Board', artist: 'Elton John', critic: 'Rolling Stone', rank: 25},
    {title: 'Marshall Mathers Lp 2', artist: 'Eminem', critic: 'Rolling Stone', rank: 24},
    {title: 'Right Thoughts Right Words Right Action', artist: 'Franz Ferdinand', critic: 'Rolling Stone', rank: 46},
    {title: 'Slow Focus', artist: 'Fuck Buttons', critic: 'Rolling Stone', rank: 48},
    {title: 'Days Are Gone', artist: 'Haim', critic: 'Rolling Stone', rank: 31},
    {title: 'Born Sinner', artist: 'J Cole', critic: 'Rolling Stone', rank: 41},
    {title: 'Jake Bugg', artist: 'Jake Bugg', critic: 'Rolling Stone', rank: 12},
    {title: 'Wrote A Song For Everyone', artist: 'John Fogerty', critic: 'Rolling Stone', rank: 10},
    {title: 'Same Trailer Different Park', artist: 'Kacey Musgraves', critic: 'Rolling Stone', rank: 28},
    {title: 'Yeezus', artist: 'Kanye West', critic: 'Rolling Stone', rank: 2},
    {title: 'Fuse', artist: 'Keith Urban', critic: 'Rolling Stone', rank: 39},
    {title: 'Wakin On A Pretty Daze', artist: 'Kurt Vile', critic: 'Rolling Stone', rank: 38},
    {title: 'Once I Was An Eagle', artist: 'Laura Marling', critic: 'Rolling Stone', rank: 20},
    {title: 'Pure Heroine', artist: 'Lorde', critic: 'Rolling Stone', rank: 7},
    {title: 'Matangi', artist: 'M.I.A.', critic: 'Rolling Stone', rank: 47},
    {title: 'Bangerz', artist: 'Miley Cyrus', critic: 'Rolling Stone', rank: 27},
    {title: 'Mbv', artist: 'My Bloody Valentine', critic: 'Rolling Stone', rank: 23},
    {title: 'The Worse Things Get The Harder I Fight The Harder I Fight The More I Love You', artist: 'Neko Case', critic: 'Rolling Stone', rank: 34},
    {title: 'Hesitation Marks', artist: 'Nine Inch Nails', critic: 'Rolling Stone', rank: 19},
    {title: 'Light Up Gold', artist: 'Parquet Courts', critic: 'Rolling Stone', rank: 11},
    {title: 'New', artist: 'Paul Mccartney', critic: 'Rolling Stone', rank: 4},
    {title: 'Lightning Bolt', artist: 'Pearl Jam', critic: 'Rolling Stone', rank: 40},
    {title: 'Bankrupt', artist: 'Phoenix', critic: 'Rolling Stone', rank: 22},
    {title: 'My Name Is My Name', artist: 'Pusha T', critic: 'Rolling Stone', rank: 33},
    {title: 'Like Clockwork', artist: 'Queens of the Stone Age', critic: 'Rolling Stone', rank: 6},
    {title: 'Silence Yourself', artist: 'Savages', critic: 'Rolling Stone', rank: 43},
    {title: 'Night Time, My Time', artist: 'Sky Ferreira', critic: 'Rolling Stone', rank: 21},
    {title: 'Heartthrob', artist: 'Tegan and Sara', critic: 'Rolling Stone', rank: 30},
    {title: 'The Terror', artist: 'The Flaming Lips', critic: 'Rolling Stone', rank: 49},
    {title: 'Trouble Will Find Me', artist: 'The National', critic: 'Rolling Stone', rank: 8},
    {title: 'Blowout', artist: 'The So So Glos', critic: 'Rolling Stone', rank: 37},
    {title: 'Pushin Against A Stone', artist: 'Valerie June', critic: 'Rolling Stone', rank: 44},
    {title: 'Modern Vampires of the City', artist: 'Vampire Weekend', critic: 'Rolling Stone', rank: 1},
    {title: 'Cerulean Salt', artist: 'Waxahatchee', critic: 'Rolling Stone', rank: 36},
    {title: 'B.O.A.T.S. II: Me Time', artist: '2 Chainz', critic: 'Spin', rank: 30},
    {title: 'Reflektor', artist: 'Arcade Fire', critic: 'Spin', rank: 37},
    {title: 'Like a Rose', artist: 'Ashley Monroe', critic: 'Spin', rank: 35},
    {title: 'Dream River', artist: 'Bill Callahan', critic: 'Spin', rank: 40},
    {title: 'Tomorrow\'s Harvest', artist: 'Boards of Canada', critic: 'Spin', rank: 7},
    {title: 'Coming Apart', artist: 'Body/Head', critic: 'Spin', rank: 48},
    {title: 'The Stand-In', artist: 'Caitlin Rose', critic: 'Spin', rank: 25},
    {title: 'Acid Rap', artist: 'Chance the Rapper', critic: 'Spin', rank: 2},
    {title: 'New History Warfare Vol. 3: To See More Light', artist: 'Colin Stetson', critic: 'Spin', rank: 41},
    {title: 'Random Access Memories', artist: 'Daft Punk', critic: 'Spin', rank: 19},
    {title: 'Old', artist: 'Danny Brown', critic: 'Spin', rank: 12},
    {title: 'Sunbather', artist: 'Deafheaven', critic: 'Spin', rank: 22},
    {title: 'Government Plates', artist: 'Death Grips', critic: 'Spin', rank: 43},
    {title: 'Settle', artist: 'Disclosure', critic: 'Spin', rank: 5},
    {title: 'I Don\'t Give a Fuck', artist: 'DJ Rashad', critic: 'Spin', rank: 24},
    {title: 'Nothing Was the Same', artist: 'Drake', critic: 'Spin', rank: 50},
    {title: 'Doris', artist: 'Earl Sweatshirt', critic: 'Spin', rank: 31},
    {title: 'The Marshall Mathers LP 2', artist: 'Eminem', critic: 'Spin', rank: 28},
    {title: 'Days Are Gone', artist: 'Haim', critic: 'Spin', rank: 4},
    {title: 'The Inheritors', artist: 'Holden', critic: 'Spin', rank: 42},
    {title: 'The Electric Lady', artist: 'Janelle Monáe', critic: 'Spin', rank: 38},
    {title: 'The 20/20 Experience', artist: 'Justin Timberlake', critic: 'Spin', rank: 32},
    {title: 'The Night\'s Gambit', artist: 'Ka', critic: 'Spin', rank: 8},
    {title: 'Same Trailer Different Park', artist: 'Kacey Musgraves', critic: 'Spin', rank: 17},
    {title: 'Yeezus', artist: 'Kanye West', critic: 'Spin', rank: 1},
    {title: 'Cut 4 Me', artist: 'Kelela', critic: 'Spin', rank: 36},
    {title: 'Wakin on a Pretty Daze', artist: 'Kurt Vile', critic: 'Spin', rank: 10},
    {title: 'Meir', artist: 'Kvelertak', critic: 'Spin', rank: 34},
    {title: 'Once I Was an Eagle', artist: 'Laura Marling', critic: 'Spin', rank: 33},
    {title: 'Matangi', artist: 'M.I.A.', critic: 'Spin', rank: 11},
    {title: 'Y.R.N.', artist: 'Migos', critic: 'Spin', rank: 27},
    {title: 'MCII', artist: 'Mikal Cronin', critic: 'Spin', rank: 18},
    {title: 'Mbv', artist: 'My Bloody Valentine', critic: 'Spin', rank: 39},
    {title: 'The Worse Things Get, the Harder I Fight, the Harder I Fight, the More I Love You ', artist: 'Neko Case', critic: 'Spin', rank: 47},
    {title: 'Hesitation Marks', artist: 'Nine Inch Nails', critic: 'Spin', rank: 15},
    {title: 'Wenu Wenu', artist: 'Omar Souleyman', critic: 'Spin', rank: 16},
    {title: 'R Plus Seven', artist: 'Oneohtrix Point Never', critic: 'Spin', rank: 23},
    {title: 'My Name is My Name', artist: 'Pusha T', critic: 'Spin', rank: 46},
    {title: 'Like Clockwork', artist: 'Queens of the Stone Age', critic: 'Spin', rank: 49},
    {title: 'Woman', artist: 'Rhye', critic: 'Spin', rank: 26},
    {title: 'Home', artist: 'Rudimental', critic: 'Spin', rank: 29},
    {title: 'Run the Jewels', artist: 'Run the Jewels', critic: 'Spin', rank: 21},
    {title: 'I Hate Music', artist: 'Superchunk', critic: 'Spin', rank: 45},
    {title: 'Heartthrob', artist: 'Tegan and Sara', critic: 'Spin', rank: 13},
    {title: 'Excavation', artist: 'The Haxan Cloak', critic: 'Spin', rank: 14},
    {title: 'Shaking the Habitual', artist: 'The Knife', critic: 'Spin', rank: 9},
    {title: 'Virgins', artist: 'Tim Hecker', critic: 'Spin', rank: 6},
    {title: 'Modern Vampires of the City', artist: 'Vampire Weekend', critic: 'Spin', rank: 3},
    {title: 'Cerulean Salt', artist: 'Waxahatchee', critic: 'Spin', rank: 20},
    {title: 'Impossible Truth', artist: 'William Tyler', critic: 'Spin', rank: 44},
    {title: 'AM', artist: 'Arctic Monkeys', critic: 'Spin - Marc Hogan ', rank: 11},
    {title: 'Yours Truly', artist: 'Ariana Grande', critic: 'Spin - Marc Hogan ', rank: 24},
    {title: 'Like a Rose', artist: 'Ashley Monroe', critic: 'Spin - Marc Hogan ', rank: 21},
    {title: 'Cupid Deluxe', artist: 'Blood Orange', critic: 'Spin - Marc Hogan ', rank: 16},
    {title: 'Desire Lines', artist: 'Camera Obscura', critic: 'Spin - Marc Hogan ', rank: 9},
    {title: 'RockaByeBaby', artist: 'Cassie', critic: 'Spin - Marc Hogan ', rank: 22},
    {title: 'Acid Rap', artist: 'Chance the Rapper', critic: 'Spin - Marc Hogan ', rank: 6},
    {title: 'True Romance', artist: 'Charli XCX', critic: 'Spin - Marc Hogan ', rank: 7},
    {title: 'The Double EP: A Sea of Split Peas', artist: 'Courtney Barnett', critic: 'Spin - Marc Hogan ', rank: 15},
    {title: 'Old', artist: 'Danny Brown', critic: 'Spin - Marc Hogan ', rank: 3},
    {title: 'Monomania', artist: 'Deerhunter', critic: 'Spin - Marc Hogan ', rank: 1},
    {title: 'Settle', artist: 'Disclosure', critic: 'Spin - Marc Hogan ', rank: 5},
    {title: 'Optimism EP', artist: 'Elizabeth Morris', critic: 'Spin - Marc Hogan ', rank: 17},
    {title: 'The Electric Lady', artist: 'Janelle Monáe', critic: 'Spin - Marc Hogan ', rank: 14},
    {title: 'Weird Sister', artist: 'Joanna Gruesome', critic: 'Spin - Marc Hogan ', rank: 19},
    {title: 'Nepenthe', artist: 'Julianna Barwick', critic: 'Spin - Marc Hogan ', rank: 20},
    {title: 'Once I Was an Eagle', artist: 'Laura Marling', critic: 'Spin - Marc Hogan ', rank: 13},
    {title: 'No Blues', artist: 'Los Campesinos!', critic: 'Spin - Marc Hogan ', rank: 12},
    {title: 'Matangi', artist: 'M.I.A.', critic: 'Spin - Marc Hogan ', rank: 4},
    {title: 'Paramore', artist: 'Paramore', critic: 'Spin - Marc Hogan ', rank: 2},
    {title: 'Night Time, My Time', artist: 'Sky Ferreira', critic: 'Spin - Marc Hogan ', rank: 10},
    {title: 'Shaking the Habitual', artist: 'The Knife', critic: 'Spin - Marc Hogan ', rank: 25},
    {title: 'Anything in Return', artist: 'Toro Y Moi', critic: 'Spin - Marc Hogan ', rank: 18},
    {title: 'Saint Heron', artist: 'Various Artists', critic: 'Spin - Marc Hogan ', rank: 8},
    {title: 'Seabed', artist: 'Vondelpark', critic: 'Spin - Marc Hogan ', rank: 23},
    {title: 'The Blow', artist: 'The Blow', critic: 'NPR - Boilen', rank: 1},
    {title: 'The Jazz Age', artist: 'The Bryan Ferry Orchestra', critic: 'NPR - Boilen', rank: 2},
    {title: 'Modern Vampires of the City', artist: 'Vampire Weekend', critic: 'NPR - Boilen', rank: 3},
    {title: 'Talon Of The Hawk', artist: 'The Front Bottoms', critic: 'NPR - Boilen', rank: 4},
    {title: 'Overgrown', artist: 'James Blake', critic: 'NPR - Boilen', rank: 5},
    {title: 'Once I Was An Eagle', artist: 'Laura Marling', critic: 'NPR - Boilen', rank: 6},
    {title: 'Woman', artist: 'Rhye', critic: 'NPR - Boilen', rank: 7},
    {title: 'For Now I Am Winter', artist: 'Ólafur Arnalds', critic: 'NPR - Boilen', rank: 8},
    {title: 'White Lighter', artist: 'Typhoon', critic: 'NPR - Boilen', rank: 9},
    {title: 'Dream River', artist: 'Bill Callahan', critic: 'NPR - Boilen', rank: 10},
    {title: 'Wildewoman', artist: 'Lucius', critic: 'NPR - Boilen', rank: 11},
    {title: 'We Are The 21st Century Ambassadors Of Peace & Magic', artist: 'Foxygen', critic: 'NPR - Boilen', rank: 12},
    {title: 'Mug Museum', artist: 'Cate Le Bon', critic: 'NPR - Boilen', rank: 13},
    {title: 'San Fermin', artist: 'San Fermin', critic: 'NPR - Boilen', rank: 14},
    {title: 'My Garden State', artist: 'Glenn Jones', critic: 'NPR - Boilen', rank: 15},
    {title: 'Open', artist: 'The Necks', critic: 'NPR - Boilen', rank: 16},
    {title: 'Amok', artist: 'Atoms For Peace', critic: 'NPR - Boilen', rank: 17},
    {title: 'Impossible Truth', artist: 'William Tyler', critic: 'NPR - Boilen', rank: 18},
    {title: 'Sing to the Moon', artist: 'Laura Mvula', critic: 'NPR - Boilen', rank: 19},
    {title: 'Nomad', artist: 'Bombino', critic: 'NPR - Boilen', rank: 20}
    ])